### PR TITLE
doc: add link to English translation README

### PR DESCRIPTION
**Pull request by JoeZijunZhou**
#207

### CODE REVIEW

**Comment by Jdev302** [comment]
I can help too if needed

**Comment by JoeZijunZhou** [comment]
@Jdev302 Awesome! So now we have a translation group translating all docs into English. After all, you will have a better understanding of the whole project. Plz checkout the English version readme. We already had a slack channel setup for eng & product. You are more than welcome to join this project! If you have questions, feel free to ask in `issues`.

**Comment by JoeZijunZhou** [comment]
@frank-zsy ready to merge, thanks!

**Pull request merged**
